name: Sync Registry
on: [push]
env:
  REPO_ORI: registry.opentext.com
  REPO_DEST: ghcr.io/chemaesteve
  LISTA: exstream-docgen:24.4.0.4686
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync From OT  Repository to GHCR Repo
      uses: onichandame/docker-registry-sync-action@master
      with:
        source_repository: ${{REPO_ORI}}/${{LISTA}}
        source_username: ${{ secrets.OTR_USERNAME }}
        source_password: ${{ secrets.OTR_PASSWORD }}
        target_repository: ${{REPO_DEST}}/${{LISTA}}}
        target_username: ${{ secrets.GHCR_USERNAME }}
        target_password: ${{ secrets.GHCR_PASSWORD }}
