name: Sync Registry
on: [push]
jobs:
  OT:
    if: False
    env:
      REPO_ORI: registry.opentext.com
      REPO_DEST: ghcr.io/chemaesteve
    strategy:
      matrix:
        LISTA: ["exstream-docgen:24.4.0.4686",
        "exstream-design:24.4.0.24361",
        "exstream-orchestration:24.4.0.6369",
        "exstream-eep-service:24.4.0.1525",
        "exstream-rationalization:24.4.0.2269"]
    runs-on: ubuntu-latest
    steps:
    - name: Sync From OT  Repository to GHCR Repo
      uses: onichandame/docker-registry-sync-action@master
      with:
        source_repository: ${{env.REPO_ORI}}/${{matrix.LISTA}}
        source_username: ${{ secrets.OTR_USERNAME }}
        source_password: ${{ secrets.OTR_PASSWORD }}
        target_repository: ${{env.REPO_DEST}}/${{matrix.LISTA}}
        target_username: ${{ secrets.GHCR_USERNAME }}
        target_password: ${{ secrets.GHCR_PASSWORD }}
  Solar:
    if: False
    env:
      REPO_ORI: docker.io/bitnami
      REPO_DEST: ghcr.io/chemaesteve
    strategy:
      matrix:
        LISTA: ["solr:9.8.0-debian-12-r1",
        "zookeeper:3.9.3-debian-12-r3"]
    runs-on: ubuntu-latest
    steps:
    - name: Sync From Solar  Repository to GHCR Repo
      uses: onichandame/docker-registry-sync-action@master
      with:
        source_repository: ${{env.REPO_ORI}}/${{matrix.LISTA}}
        target_repository: ${{env.REPO_DEST}}/${{matrix.LISTA}}
        target_username: ${{ secrets.GHCR_USERNAME }}
        target_password: ${{ secrets.GHCR_PASSWORD }}
  Charts:
    if: False
    env:
      REPO_ORI: oci://registry-1.docker.io/bitnamicharts
      REPO_DEST: oci://ghcr.io/chemaesteve
    strategy:
      matrix:
        LISTA: ["solr:9.5.3"]
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: REPO_DEST
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - name: Pull and Push Chart to GHCR Repo
        run: |
          helm pull ${{env.REPO_ORI}}/${{matrix.LISTA}}
          pck=$(echo ${{matrix.LISTA}}.tgz | sed s/:/-/g)
          helm push  $pck ${{env.REPO_DEST}}
  ChartsOT:
    if: True
    env:
      REPO_ORI: oci://registry.opentext.com
      REPO_DEST: oci://ghcr.io/chemaesteve
    strategy:
      matrix:
        LISTA: ["helm"]
    runs-on: ubuntu-latest
    steps:
      - name: Login to OT Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.REPO_ORI}}
          username: ${{ secrets.OTR_USERNAME }}
          password: ${{ secrets.OTR_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.REPO_DEST}}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - name: Pull and Push Chart to GHCR Repo
        run: |
          helm pull ${{env.REPO_ORI}}/${{matrix.LISTA}}
          pck=$(echo ${{matrix.LISTA}}.tgz | sed s/:/-/g)
          helm push  $pck ${{env.REPO_DEST}}
