name: Sync Registry
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync From OT Repository to GHCR Repo
      uses: onichandame/docker-registry-sync-action@master
      with:
        source_repository: registry.opentext.com/otds-server:24.4.0
        source_username: ${{ secrets.OT_USERNAME }}
        source_password: ${{ secrets.OT_PASSWORD }}
        target_repository: /otds-server:24.4.0
        target_username: ${{ secrets.GHCR_USERNAME }}
        target_password: ${{ secrets.GHCR_PASSWORD }}
