name: Sync Registry
on: [push]
jobs:
  OT:
    env:
      REPO_ORI: registry.opentext.com
      REPO_DEST: ghcr.io/chemaesteve
    strategy:
      matrix:
        LISTA: []
    runs-on: ubuntu-latest
    steps:
    - name: Sync From OT  Repository to GHCR Repo
      uses: onichandame/docker-registry-sync-action@master
      with:
        source_repository: ${{env.REPO_ORI}}/${{matrix.LISTA}}
        source_username: ${{ secrets.OTR_USERNAME }}
        source_password: ${{ secrets.OTR_PASSWORD }}
        target_repository: ${{env.REPO_DEST}}/${{matrix.LISTA}}
        target_username: ${{ secrets.GHCR_USERNAME }}
        target_password: ${{ secrets.GHCR_PASSWORD }}
  Solar:
    env:
      REPO_ORI: docker.io/bitnami
      REPO_DEST: ghcr.io/chemaesteve
    strategy:
      matrix:
        LISTA: ["solr:9.8.0-debian-12-r1",
        "zookeeper:3.9.3-debian-12-r3"]
    runs-on: ubuntu-latest
    steps:
    - name: Sync From Solar  Repository to GHCR Repo
      uses: onichandame/docker-registry-sync-action@master
      with:
        source_repository: ${{env.REPO_ORI}}/${{matrix.LISTA}}
        target_repository: ${{env.REPO_DEST}}/${{matrix.LISTA}}
        target_username: ${{ secrets.GHCR_USERNAME }}
        target_password: ${{ secrets.GHCR_PASSWORD }}
